name: C/C++ CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.gitignore'

jobs:
  build:

    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]

    steps:
    - uses: actions/checkout@v2
    - name: install binutils-dev and libiberty-dev ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install binutils-dev libiberty-dev -y
    #- name: install binutils macOs
    #  if: matrix.os == 'macOs-latest'
    #  run: brew install binutils
    - name: configure
      run: cmake . -B build -DBUILD_TESTS=ON
    - name: make
      run: cmake --build build
    - name: run test unix
      run: ./stacktrace_test
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOs-latest'
      working-directory: build
    - name: run test windows
      run: stacktrace_test.exe
      if: matrix.os == 'windows-latest'
      working-directory: build/Debug
      shell: cmd
